Task1: csc4421_er0471_Joy_Evans_Lab05Task1.c
	gcc -o Task1 csc4421_er0471_Joy_Evans_Lab05Task1.c
Task2: csc4421_er0471_Joy_Evans_Lab05Task2.c
	gcc -o Task2 csc4421_er0471_Joy_Evans_Lab05Task2.c
Task3: csc4421_er0471_Joy_Evans_Lab05Task3.c
	gcc -o Task3 csc4421_er0471_Joy_Evans_Lab05Task3.c
